export const ERROR_MESSAGES = {
  MISSING_SERVICE_NAME: 'ERROR_MISSING_SERVICE_NAME',
  MISSING_ENVIRONMENT: 'ERROR_MISSING_ENVIRONMENT',
  MISSING_EMIT_FUNCTION: 'ERROR_MISSING_EMIT_FUNCTION',
  MISSING_REGISTER_HANDLER: 'ERROR_MISSING_REGISTER_HANDLER',
  SERVICE_NOT_INITIALIZED: 'ERROR_SERVICE_NOT_INITIALIZED',
  HANDLING_EVENT: 'ERROR_HANDLING_EVENT',
  HANDLING_TASK: 'ERROR_HANDLING_TASK',
  HANDLING_INSTANCE_TASK: 'ERROR_HANDLING_INSTANCE_TASK',
  REGISTERING_EVENT: 'ERROR_REGISTERING_EVENT',
  REGISTERING_TASK: 'ERROR_REGISTERING_TASK',
  REGISTERING_INSTANCE_TASK: 'ERROR_REGISTERING_INSTANCE_TASK',
};
